### ISSUE TITLE
`vite-plugin-conditional-compile` fails to import named export 'traverse' from `@babel/core`

### ISSUE THREAD

**Issue by f4-miyata** [LZS911/vite-plugin-conditional-compile#2]
### Bug Description
When trying to run my project with `vite-plugin-conditional-compile`, I encounter an error stating that the named export 'traverse' cannot be found in the `@babel/core` module. The error message suggests that `@babel/core` is a CommonJS module, which may not support all module.exports as named exports.

This issue is preventing my project from starting in development mode using Vite and vite-plugin-conditional-compile.

### Steps to Reproduce
1. Install `vite-plugin-conditional-compile` in a project that uses Vite.
2. Run the project.
3. See error.

### Environment
- OS: macOS
- Node.js version: 20.10.0
- Vite version: 5.1.4
- vite-plugin-conditional-compile version: 1.4.3
- Package Manager: pnpm

### Additional Context
Here is the error message I receive:

```
SyntaxError: Named export 'traverse' not found. The requested module '@babel/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@babel/core';
const { parseSync, traverse } = pkg;
```

### Acknowledgements
Thank you for maintaining the `vite-plugin-conditional-compile` plugin. It's been instrumental in our development process, and we appreciate the effort put into making it work seamlessly with Vite.

**Comment by LZS911** [comment]
version 1.4.4 has been released and can be used normally in ESModule after testing.

**Comment by f4-miyata** [comment]
@LZS911 
Thank you for addressing this issue so promptly. 
I'm grateful for the effort to upgrade the @babel-core package and find a resolution.
After updating to version 1.4.4, I can confirm the issue has been resolved and it now works perfectly in ESModule.
Thank you for your support and swift response.
